package dev.tberghuis.voicememos.tmp.tmp01

import android.content.Context
import android.media.AudioFormat
import android.net.Uri
import androidx.annotation.OptIn
import androidx.media3.common.MediaItem
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.DataSource
import androidx.media3.datasource.DataSpec
import androidx.media3.datasource.FileDataSource
import androidx.media3.datasource.TransferListener
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.exoplayer.source.ProgressiveMediaSource
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

class TmpAudioController(val context: Context) {

  // this was generated by AI
  @OptIn(UnstableApi::class)
  suspend fun play(filename: String) = withContext(Dispatchers.Main) {
    val file = File(context.filesDir, filename)
    if (!file.exists()) return@withContext

    val player = ExoPlayer.Builder(context).build()

    val header = createWavHeader(file.length())

    val dataSourceFactory = DataSource.Factory {
      val fileDataSource = FileDataSource()
      object : DataSource {
        private var headerBytesRead = 0

        override fun addTransferListener(transferListener: TransferListener) {
          fileDataSource.addTransferListener(transferListener)
        }

        override fun open(dataSpec: DataSpec): Long {
          fileDataSource.open(DataSpec(Uri.fromFile(file)))
          return header.size + file.length()
        }

        override fun read(buffer: ByteArray, offset: Int, length: Int): Int {
          if (headerBytesRead < header.size) {
            val bytesToRead = minOf(length, header.size - headerBytesRead)
            System.arraycopy(header, headerBytesRead, buffer, offset, bytesToRead)
            headerBytesRead += bytesToRead
            return bytesToRead
          }
          return fileDataSource.read(buffer, offset, length)
        }

        override fun getUri(): Uri? = Uri.fromFile(file)

        override fun close() {
          fileDataSource.close()
        }
      }
    }

    val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
      .createMediaSource(MediaItem.fromUri(Uri.fromFile(file)))

    player.setMediaSource(mediaSource)
    player.prepare()
    player.play()

    val deferred = CompletableDeferred<Unit>()
    val listener = object : Player.Listener {
      override fun onPlaybackStateChanged(state: Int) {
        if (state == Player.STATE_ENDED) {
          deferred.complete(Unit)
        }
      }

      override fun onPlayerError(error: androidx.media3.common.PlaybackException) {
        deferred.completeExceptionally(error)
      }
    }
    player.addListener(listener)

    try {
      deferred.await()
    } finally {
      player.removeListener(listener)
      player.release()
    }
  }

  private fun createWavHeader(pcmAudioSize: Long): ByteArray {
    val header = ByteArray(44)
    val totalAudioLen = pcmAudioSize + 36
    val sampleRate = RECORDING_RATE.toLong()
    val channels = 1
    val byteRate = sampleRate * channels * 2

    header[0] = 'R'.code.toByte()
    header[1] = 'I'.code.toByte()
    header[2] = 'F'.code.toByte()
    header[3] = 'F'.code.toByte()
    header[4] = (totalAudioLen and 0xff).toByte()
    header[5] = ((totalAudioLen shr 8) and 0xff).toByte()
    header[6] = ((totalAudioLen shr 16) and 0xff).toByte()
    header[7] = ((totalAudioLen shr 24) and 0xff).toByte()
    header[8] = 'W'.code.toByte()
    header[9] = 'A'.code.toByte()
    header[10] = 'V'.code.toByte()
    header[11] = 'E'.code.toByte()
    header[12] = 'f'.code.toByte()
    header[13] = 'm'.code.toByte()
    header[14] = 't'.code.toByte()
    header[15] = ' '.code.toByte()
    header[16] = 16
    header[17] = 0
    header[18] = 0
    header[19] = 0
    header[20] = 1
    header[21] = 0
    header[22] = channels.toByte()
    header[23] = 0
    header[24] = (sampleRate and 0xff).toByte()
    header[25] = ((sampleRate shr 8) and 0xff).toByte()
    header[26] = ((sampleRate shr 16) and 0xff).toByte()
    header[27] = ((sampleRate shr 24) and 0xff).toByte()
    header[28] = (byteRate and 0xff).toByte()
    header[29] = ((byteRate shr 8) and 0xff).toByte()
    header[30] = ((byteRate shr 16) and 0xff).toByte()
    header[31] = ((byteRate shr 24) and 0xff).toByte()
    header[32] = (channels * 2).toByte()
    header[33] = 0
    header[34] = 16
    header[35] = 0
    header[36] = 'd'.code.toByte()
    header[37] = 'a'.code.toByte()
    header[38] = 't'.code.toByte()
    header[39] = 'a'.code.toByte()
    header[40] = (pcmAudioSize and 0xff).toByte()
    header[41] = ((pcmAudioSize shr 8) and 0xff).toByte()
    header[42] = ((pcmAudioSize shr 16) and 0xff).toByte()
    header[43] = ((pcmAudioSize shr 24) and 0xff).toByte()
    return header
  }

  companion object {
    const val RECORDING_RATE = 8000 // can go up to 44K, if needed
    const val CHANNEL_IN = AudioFormat.CHANNEL_IN_MONO
    const val CHANNELS_OUT = AudioFormat.CHANNEL_OUT_MONO
    const val FORMAT = AudioFormat.ENCODING_PCM_16BIT
  }
}